### ISSUE TITLE
RNA seq reads not working

### ISSUE THREAD

**Issue by jianshu93** [KGerhardt/multitrim#2]
For RNA seq reads,  I have the following error:

The output /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/metaT/01.trimmed_multitrim/Ind6/Ind6_Subsample_Adapter_Detection.stats.txt file exists and will be overwritten.
Traceback (most recent call last):
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/multitrim/bin/multitrim", line 11, in <module>
    sys.exit(main())
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/multitrim/lib/python3.7/site-packages/multitrim/multitrim.py", line 1185, in main
    cleaned_adapters = parse_adapters(adapter_set, adapters_detected, final_output, prefix)
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/envs/multitrim/lib/python3.7/site-packages/multitrim/multitrim.py", line 568, in parse_adapters
    detected_seqs[id] = full_list[id]
KeyError: 'cre-loxp-forward'

out:
Primary Strand Reads: /storage/home/hcoda1/4/jzhao399/shared-p/RNAseq_Test/FASTQ_Generation_12_30_2019_1756994-199358612/01.raw_reads/Ind6.1.fastq.gz 
Reverse Strand Reads: /storage/home/hcoda1/4/jzhao399/shared-p/RNAseq_Test/FASTQ_Generation_12_30_2019_1756994-199358612/01.raw_reads/Ind6.2.fastq.gz
Adapters considered detected if present in 0.1 % of reads.
Subsampling: /storage/home/hcoda1/4/jzhao399/shared-p/RNAseq_Test/FASTQ_Generation_12_30_2019_1756994-199358612/01.raw_reads/Ind6.1.fastq.gz
Subsampling: /storage/home/hcoda1/4/jzhao399/shared-p/RNAseq_Test/FASTQ_Generation_12_30_2019_1756994-199358612/01.raw_reads/Ind6.2.fastq.gz
Detecting adapters now... Detection done!
Creating specific adapters file for you.

[Ind1_Subsample_Adapter_Detection.stats.txt](https://github.com/KGerhardt/multitrim/files/6046769/Ind1_Subsample_Adapter_Detection.stats.txt)

Raw reads file
****/shared-p/RNAseq_Test/FASTQ_Generation_12_30_2019_1756994-199358612/01.raw_reads

I can run them with enveomics trim.pbs pipeline. I will go with the trim.pbs first but let you know this error.

a very low proportion of adaptors was detected? And it just stopped because nothing to trim?

Thanks,

Jianshu

**Comment by KGerhardt** [comment]
No adapters detected should be fine. Interesting. It should be fine with not finding a sequence. Zero adapters detected and an empty fasta file are both OK with multitrim and both FaQCs and fastp.

That missing key error shouldn't come up, since the full_list is based on your input adapter sequences. Can you send me the list you used?

**Comment by jianshu93** [comment]
I actually uses the default adaptor by MiGA as you noted in the -adaptor option (There should be some adaptors for RNA sequencing in the default list right?)

Jianshu

**Comment by KGerhardt** [comment]
There are RNA adapters in there. The current list is at: https://github.com/bio-miga/miga/blob/main/utils/adapters.fa

Did you supply anything to the --adapters argument, or was it left unused? It works for me by default, but perhaps I missed something?

**Comment by KGerhardt** [comment]
Okay, so I went and read the FaQCs code, as FaQCs is used to ID adapters. When FaQCs is supplied with adapters, adapter trimming (by default off) is forced on.

 Apparently, even when you supply FaQCs with a list of adapters, it *also* includes its own internal adapter list. This list included the cre-loxp adapter set that caused the error you saw. Those adapters were NOT part of MiGA's list, so when multitrim attempted to look up their sequence when trimming, it couldn't find them.

I am adding these sequences to the multitrim list and will shortly upload the fixed code.
